### ISSUE TITLE
Test MP photo/pess with accuracy settings

### ISSUE THREAD

**Issue by santiagocasas** [lesgourg/Euclid_KP_nu#1]
Settings suggested by @lesgourg :

```
-data.cosmo_arguments['l_max_ncdm'] = 22
-data.cosmo_arguments['ncdm_fluid_trigger_tau_over_tau_k'] = 41.
+data.cosmo_arguments['l_max_ncdm'] = 30
+data.cosmo_arguments['ncdm_fluid_trigger_tau_over_tau_k'] = 100.
 
+data.cosmo_arguments['tol_ncdm_bg'] = 1.e-10
+data.cosmo_arguments['tol_M_ncdm'] = 1.e-10
```

@Sefa76  can test the effect on montepyhton_fisher of varying the stepsize for Mnu (0.1sigma, 0.2sigma...) with/without these additional settings.

**Comment by Sefa76** [comment]
I did not test everything with these precision settings but varying the step size and fixing my .param did the job. Now pess and opt are agreeing w.r.t. Cosmicfish.
[table_photo_pess.pdf](https://github.com/lesgourg/Euclid_KP_nu/files/10168476/table_photo_pess.pdf)
[table_photo_opt.pdf](https://github.com/lesgourg/Euclid_KP_nu/files/10168477/table_photo_opt.pdf)
[WLxGCPh_Pess_cosmo.pdf](https://github.com/lesgourg/Euclid_KP_nu/files/10168483/WLxGCPh_Pess_cosmo.pdf)
[WLxGCPh_Opt_cosmo.pdf](https://github.com/lesgourg/Euclid_KP_nu/files/10168484/WLxGCPh_Opt_cosmo.pdf)

**Comment by Sefa76** [comment]
[sigmaSteptesting_cosmo_and_nuisance_error_comparison.pdf](https://github.com/lesgourg/Euclid_KP_nu/files/10177288/sigmaSteptesting_cosmo_and_nuisance_error_comparison.pdf)
here i tested the effect of different step-sizes of m_nu in Photo Opt , the points labeled  \sigma ... are MP-Fishermode. It seems like we can just use 0.1 Sigma for the Stepsize for Neutrino masses in MP-Fisher aswell
